"""Preset audio catalog for Floppy seed/pregen.

Source: docs/preset_audio_catalog_v0.md (24 items by algo).
provider_strategy: "minimax" for TTS-readable, "local" for placeholder.
is_placeholder: True for white_noise/music (no real audio yet).
"""

from __future__ import annotations

AUDIO_CATALOG: list[dict] = [
    # =========================================================================
    # WHITE NOISE (6) — all placeholder
    # =========================================================================
    {"title": "夜雨轻敲", "audio_type": "white_noise", "request_text": "轻柔夜雨声白噪音，安静入睡，30分钟", "script_text": None, "duration_sec": 1800, "tags": ["rain", "ambient", "nature", "low_stimulation"], "mood_tags": ["calm", "safe"], "user_segment_tags": ["environmental_sleep", "anxiety_relief"], "quality_score": 0.82, "provider_strategy": "local", "is_placeholder": True, "voice_style": None},
    {"title": "远处海浪", "audio_type": "white_noise", "request_text": "远处海浪声白噪音，平稳持续，30分钟", "script_text": None, "duration_sec": 1800, "tags": ["ocean", "ambient", "nature", "minimal_voice"], "mood_tags": ["calm"], "user_segment_tags": ["environmental_sleep", "balanced_sleep"], "quality_score": 0.80, "provider_strategy": "local", "is_placeholder": True, "voice_style": None},
    {"title": "山间溪流", "audio_type": "white_noise", "request_text": "山间溪流自然音，清澈平静，20分钟", "script_text": None, "duration_sec": 1200, "tags": ["ambient", "nature", "low_stimulation"], "mood_tags": ["calm", "gentle"], "user_segment_tags": ["environmental_sleep", "quick_sleep"], "quality_score": 0.80, "provider_strategy": "local", "is_placeholder": True, "voice_style": None},
    {"title": "温暖壁炉", "audio_type": "white_noise", "request_text": "壁炉火焰噼啪声，温暖安心，30分钟", "script_text": None, "duration_sec": 1800, "tags": ["ambient", "low_stimulation"], "mood_tags": ["safe"], "user_segment_tags": ["environmental_sleep", "companionship"], "quality_score": 0.79, "provider_strategy": "local", "is_placeholder": True, "voice_style": None},
    {"title": "深夜森林", "audio_type": "white_noise", "request_text": "深夜森林虫鸣和微风，25分钟", "script_text": None, "duration_sec": 1500, "tags": ["nature", "ambient", "minimal_voice", "low_stimulation"], "mood_tags": ["calm"], "user_segment_tags": ["environmental_sleep", "anxiety_relief"], "quality_score": 0.80, "provider_strategy": "local", "is_placeholder": True, "voice_style": None},
    {"title": "空调白噪音", "audio_type": "white_noise", "request_text": "单调空调风扇白噪音，20分钟", "script_text": None, "duration_sec": 1200, "tags": ["ambient", "low_stimulation", "short_duration"], "mood_tags": ["calm"], "user_segment_tags": ["environmental_sleep", "quick_sleep"], "quality_score": 0.78, "provider_strategy": "local", "is_placeholder": True, "voice_style": None},
    # =========================================================================
    # MUSIC (6) — all placeholder
    # =========================================================================
    {"title": "月光钢琴曲", "audio_type": "music", "request_text": "轻柔钢琴曲，适合睡前放松，20分钟", "script_text": None, "duration_sec": 1200, "tags": ["ambient", "minimal_voice", "slow_pace", "low_stimulation"], "mood_tags": ["calm"], "user_segment_tags": ["environmental_sleep", "balanced_sleep"], "quality_score": 0.81, "provider_strategy": "local", "is_placeholder": True, "voice_style": None},
    {"title": "大提琴安眠曲", "audio_type": "music", "request_text": "温暖大提琴安眠曲，15分钟", "script_text": None, "duration_sec": 900, "tags": ["ambient", "slow_pace", "low_stimulation"], "mood_tags": ["safe", "gentle"], "user_segment_tags": ["companionship", "anxiety_relief"], "quality_score": 0.80, "provider_strategy": "local", "is_placeholder": True, "voice_style": None},
    {"title": "古筝流水", "audio_type": "music", "request_text": "古筝流水意境轻音乐，20分钟", "script_text": None, "duration_sec": 1200, "tags": ["nature", "ambient", "slow_pace", "low_stimulation"], "mood_tags": ["calm"], "user_segment_tags": ["environmental_sleep", "balanced_sleep"], "quality_score": 0.80, "provider_strategy": "local", "is_placeholder": True, "voice_style": None},
    {"title": "吉他轻弹", "audio_type": "music", "request_text": "温暖吉他轻弹，安静助眠，15分钟", "script_text": None, "duration_sec": 900, "tags": ["ambient", "minimal_voice", "low_stimulation"], "mood_tags": ["gentle"], "user_segment_tags": ["companionship", "balanced_sleep"], "quality_score": 0.79, "provider_strategy": "local", "is_placeholder": True, "voice_style": None},
    {"title": "长笛晨雾", "audio_type": "music", "request_text": "长笛配自然晨雾感，10分钟", "script_text": None, "duration_sec": 600, "tags": ["nature", "ambient", "short_duration", "low_stimulation"], "mood_tags": ["calm"], "user_segment_tags": ["quick_sleep", "environmental_sleep"], "quality_score": 0.78, "provider_strategy": "local", "is_placeholder": True, "voice_style": None},
    {"title": "弦乐小夜曲", "audio_type": "music", "request_text": "弦乐小夜曲，温柔舒展，25分钟", "script_text": None, "duration_sec": 1500, "tags": ["ambient", "slow_pace", "low_stimulation"], "mood_tags": ["safe", "gentle"], "user_segment_tags": ["companionship", "balanced_sleep"], "quality_score": 0.80, "provider_strategy": "local", "is_placeholder": True, "voice_style": None},
    # =========================================================================
    # MEDITATION (6) — MiniMax TTS
    # =========================================================================
    {"title": "呼吸觉察·雨夜版", "audio_type": "meditation", "request_text": "温柔女声呼吸冥想配轻微雨声，焦虑舒缓，10分钟", "script_text": "现在，让我们开始今晚的呼吸练习。<#4#>轻轻闭上眼睛。<#5#>把注意力放到呼吸上。<#4#>吸气。<#5#>呼气。<#4#>不需要改变节奏。<#5#>只是注意到它。<#6#>吸气时，感受空气进入鼻腔的凉意。<#5#>呼气时，感受身体轻轻放松。<#6#>外面有轻柔的雨声。<#4#>每一滴雨都在帮你冲洗今天的疲惫。<#6#>继续呼吸。<#5#>吸气。<#6#>呼气。<#8#>你是安全的。<#10#>", "duration_sec": 600, "tags": ["breathing", "low_stimulation", "rain", "warm_voice", "slow_pace", "grounding", "short_duration", "minimal_voice"], "mood_tags": ["anxiety_relief", "calm"], "user_segment_tags": ["anxiety_relief", "quick_sleep"], "quality_score": 0.88, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "gentle_female"},
    {"title": "身体扫描放松", "audio_type": "meditation", "request_text": "引导式身体扫描冥想，从头到脚逐步放松，15分钟", "script_text": "欢迎来到今晚的放松练习。<#3#>找一个舒服的姿势躺好。<#5#>我们从头顶开始。<#4#>感受头皮慢慢放松。<#5#>眉头松开。<#4#>眼睛不再用力。<#5#>嘴角自然下垂。<#6#>脖子两侧的紧张感正在消散。<#5#>肩膀沉入枕头。<#6#>双臂变得温暖而沉重。<#5#>指尖微微发麻。<#6#>腹部随呼吸轻轻起伏。<#5#>髋部放松。<#5#>双腿彻底松软。<#6#>脚趾舒展。<#8#>整个身体都被温暖包裹着。<#10#>", "duration_sec": 900, "tags": ["grounding", "breathing", "slow_pace", "low_stimulation", "warm_voice"], "mood_tags": ["anxiety_relief", "calm"], "user_segment_tags": ["anxiety_relief", "balanced_sleep"], "quality_score": 0.86, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "gentle_female"},
    {"title": "正念当下·森林", "audio_type": "meditation", "request_text": "森林正念冥想，觉察当下，12分钟", "script_text": "此刻，你走进一片安静的森林。<#4#>脚下是柔软的落叶。<#5#>远处有鸟在轻声歌唱。<#4#>微风带来松木的气息。<#5#>你找到一棵大树，靠着它坐下。<#6#>闭上眼睛。<#5#>感受背后树干的温度。<#6#>你不需要去任何地方。<#5#>不需要做任何事。<#6#>只是在这里。<#5#>呼吸变得缓慢而深长。<#6#>森林接住了你所有的重量。<#8#>", "duration_sec": 720, "tags": ["nature", "breathing", "grounding", "slow_pace", "low_stimulation", "warm_voice"], "mood_tags": ["calm", "safe"], "user_segment_tags": ["anxiety_relief", "companionship"], "quality_score": 0.85, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "whisper_female"},
    {"title": "入睡倒计时", "audio_type": "meditation", "request_text": "极简入睡引导，高密度停顿，8分钟快速入睡", "script_text": "十。<#6#>呼气。<#8#>九。<#6#>身体更沉。<#8#>八。<#7#>放松。<#9#>七。<#7#>不需要数。<#10#>六。<#8#>眼皮很重。<#10#>五。<#9#>快了。<#12#>四。<#10#>三。<#12#>二。<#15#>", "duration_sec": 480, "tags": ["slow_pace", "short_duration", "low_stimulation", "minimal_voice"], "mood_tags": ["calm"], "user_segment_tags": ["quick_sleep", "anxiety_relief"], "quality_score": 0.84, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "whisper_female"},
    {"title": "慈心冥想·温暖", "audio_type": "meditation", "request_text": "慈心冥想引导，给自己温暖和善意，15分钟", "script_text": "今晚，我们来做一个关于温暖的练习。<#4#>闭上眼睛。<#5#>想象心口有一团柔和的光。<#5#>它是温暖的。<#4#>现在，对自己说。<#5#>愿我平安。<#6#>愿我快乐。<#6#>愿我安睡。<#5#>感受这些话在心里回荡。<#6#>你值得被温柔对待。<#5#>你今天已经很努力了。<#6#>现在可以休息了。<#8#>光慢慢扩大，包裹住整个身体。<#10#>", "duration_sec": 900, "tags": ["warm_voice", "slow_pace", "low_stimulation", "grounding"], "mood_tags": ["safe", "gentle"], "user_segment_tags": ["companionship", "anxiety_relief"], "quality_score": 0.85, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "gentle_female"},
    {"title": "海边呼吸引导", "audio_type": "meditation", "request_text": "海边呼吸冥想引导，跟随海浪节奏呼吸，10分钟", "script_text": "想象你坐在一片安静的海边。<#4#>海浪轻轻涌来。<#5#>退去。<#5#>再涌来。<#6#>让呼吸跟随海浪的节奏。<#5#>海浪涌来时，吸气。<#6#>海浪退去时，呼气。<#6#>不需要用力。<#5#>海浪会带着你。<#6#>吸。<#7#>呼。<#7#>吸。<#8#>呼。<#9#>很好。<#10#>", "duration_sec": 600, "tags": ["breathing", "ocean", "low_stimulation", "warm_voice", "nature", "slow_pace"], "mood_tags": ["calm"], "user_segment_tags": ["anxiety_relief", "environmental_sleep"], "quality_score": 0.86, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "gentle_female"},
    # =========================================================================
    # STORY (4) + PODCAST_DIGEST (2) — MiniMax TTS
    # =========================================================================
    {"title": "海边书店的夜晚", "audio_type": "story", "request_text": "温柔女声讲海边书店的安静夜晚，15分钟", "script_text": "在一个安静的海边小镇，有一家旧书店。<#3#>傍晚时分，最后一个客人离开了。<#4#>店主没有关灯。<#5#>她喜欢在这种时候，独自坐在窗边。<#4#>远处的海浪声透过半开的窗户传进来。<#5#>书架上的书安静地排列着，像在等什么。<#4#>她随手翻开一本。<#5#>纸张的气味混合着海风。<#6#>故事里写着一个人在傍晚走进一家书店。<#5#>她笑了笑。<#4#>就像此刻。<#6#>暖黄的灯光落在书页上。<#5#>窗外的海浪声越来越轻。<#8#>她的眼皮慢慢合上。<#10#>", "duration_sec": 900, "tags": ["warm_voice", "gentle_story", "voice_present", "narrative", "slow_pace", "ocean"], "mood_tags": ["safe", "gentle"], "user_segment_tags": ["companionship", "balanced_sleep"], "quality_score": 0.87, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "storyteller_female"},
    {"title": "猫与旧阁楼", "audio_type": "story", "request_text": "一只猫在旧阁楼发现秘密的温暖故事，12分钟", "script_text": "在城市的某个老房子里，有一个被遗忘的阁楼。<#3#>一只灰色的猫找到了通往那里的楼梯。<#4#>阁楼里很暗，但很温暖。<#5#>角落堆着旧箱子和发黄的报纸。<#4#>猫跳上一个木箱。<#5#>箱子里面有一条围巾，柔软而温暖。<#4#>猫把自己卷进去。<#6#>窗外传来远处的钟声。<#5#>阁楼里的灰尘在最后一缕光线中浮动。<#6#>猫闭上了眼睛。<#5#>这是它的秘密基地。<#8#>没有人知道。<#10#>", "duration_sec": 720, "tags": ["warm_voice", "gentle_story", "voice_present", "narrative", "slow_pace"], "mood_tags": ["gentle", "safe"], "user_segment_tags": ["companionship", "balanced_sleep"], "quality_score": 0.86, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "storyteller_female"},
    {"title": "星空列车慢行记", "audio_type": "story", "request_text": "一列穿越星空的列车的奇幻睡前故事，20分钟", "script_text": "夜深了，站台上只剩你一个人。<#3#>一列没有编号的列车缓缓驶来。<#4#>车门打开，里面是暖黄色的灯光。<#5#>你走了进去。<#4#>列车开始移动，越来越快。<#5#>窗外的城市变成了星空。<#6#>你靠在柔软的座椅上。<#5#>车厢里很安静。<#4#>偶尔能听到轨道轻轻的咔哒声。<#6#>窗外的星星在缓缓流动。<#5#>列车没有目的地。<#6#>它只是在星星之间慢慢行驶。<#8#>你可以在任何时候睡着。<#10#>", "duration_sec": 1200, "tags": ["warm_voice", "gentle_story", "voice_present", "narrative", "slow_pace"], "mood_tags": ["calm", "safe"], "user_segment_tags": ["companionship", "balanced_sleep"], "quality_score": 0.86, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "warm_female"},
    {"title": "雨夜城市漫步", "audio_type": "story", "request_text": "雨夜在安静城市散步的温柔叙事，15分钟", "script_text": "今晚下着小雨。<#3#>你撑着伞，走在安静的街上。<#4#>路灯把雨丝照得发亮。<#5#>地面倒映着暖色的光。<#4#>没有车。<#5#>没有行人。<#4#>只有你和雨声。<#6#>你经过一家面包店，虽然已经关门了。<#5#>空气里还有淡淡的烘焙香。<#6#>雨落在伞上的声音很轻很轻。<#5#>像有人在说：今天辛苦了。<#6#>你笑了笑，继续走着。<#8#>不着急回家。<#10#>", "duration_sec": 900, "tags": ["warm_voice", "gentle_story", "voice_present", "narrative", "slow_pace", "rain"], "mood_tags": ["calm"], "user_segment_tags": ["companionship", "environmental_sleep"], "quality_score": 0.86, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "warm_female"},
    {"title": "科技简报·助眠版", "audio_type": "podcast_digest", "request_text": "用平和声音讲几条科技短讯，低信息密度，10分钟", "script_text": "今天有几条轻松的科技消息。<#3#>科学家发现了一种能发光的蘑菇。<#4#>它们在深夜的森林里闪着淡绿色的光。<#5#>没人知道为什么，但很美。<#6#>另外，有人设计了一个帮助流浪猫找到家的小程序。<#5#>据说已经帮了一百多只猫。<#6#>嗯，其实这些也不急。<#5#>明天再想也来得及。<#8#>今晚先好好睡觉。<#10#>", "duration_sec": 600, "tags": ["voice_present", "narrative", "slow_pace", "low_stimulation"], "mood_tags": ["calm"], "user_segment_tags": ["content_transform", "balanced_sleep"], "quality_score": 0.82, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "podcast_male"},
    {"title": "历史小故事·古丝路", "audio_type": "podcast_digest", "request_text": "温柔讲述古丝绸之路的小故事，12分钟", "script_text": "很久以前，有一条连接东西方的路。<#3#>人们叫它丝绸之路。<#4#>不是真的铺满丝绸。<#5#>而是商人们带着丝绸、茶叶和瓷器，走过沙漠和山脉。<#6#>路很长。<#5#>有时候走几个月才到下一个城市。<#6#>但路上有驿站。<#5#>有水。<#4#>有同行的人。<#6#>他们在夜晚的篝火旁讲故事。<#5#>讲自己从哪里来。<#6#>讲要去哪里。<#8#>后来这些故事也跟着丝绸一起，到了很远的地方。<#10#>", "duration_sec": 720, "tags": ["voice_present", "narrative", "slow_pace", "low_stimulation"], "mood_tags": ["calm", "gentle"], "user_segment_tags": ["content_transform", "companionship"], "quality_score": 0.82, "provider_strategy": "minimax", "is_placeholder": False, "voice_style": "storyteller_male"},
]
